### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by mp1pro** [atimofte10/codeflix#1]
Criteria 1: Report:

    Score Level: 3 (Needs Improvement)
    Comment(s): The overall report on the data was great. Each response should have a data table, SQL query and an explanation. After the first question, the reports did not have the corresponding sql queries. 

Criteria 2: Query Accuracy

    Score Level: 4 (Exceeds Expectations)
    Comment(s): All queries accurately retrieve the data intended.

Criteria 3: Query Formatting

    Score Level: 4 (Exceeds Expectations)
    Comment(s): Queries are formatted according to the SQL style guide.

Criteria 4: Understanding underlying concepts and terminology

    Score Level: 4 (Exceeds Expectations)
    Comment(s): Report demonstrates a clear mastery of calculating and analyzing churn rates. the conclusion and commentary given for the final conclusion is on point. 

Overall Score: 15/16

**Comment by AnaTimofte** [comment]
Thank you for the feedback!
